FROM golang:1.22

WORKDIR /app
COPY go.mod go.sum ./

CMD go mod download && \
    go run github.com/cosmtrek/air@v1.43.0 \
    --build.cmd "go build -o=/tmp/bin/aws-storage ./src" --build.bin "/tmp/bin/aws-storage" --build.delay "100" \
    --build.exclude_dir "" \
    --build.include_ext "go, tpl, tmpl, html, css, scss, js, ts, sql, jpeg, jpg, gif, png, bmp, svg, webp, ico" \
    --misc.clean_on_exit "true"